[workspace]
members = [".", "wikitext_simplified", "wikitext_util"]

[workspace.dependencies]
parse-wiki-text-2 = { git = "https://github.com/philpax/parse-wiki-text-2.git", branch = "wasm-support", features = [
    "wasm",
] }
serde = { version = "1.0.217", features = ["derive"] }

[package]
name = "genresinspace"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bzip2 = "0.5.0"
quick-xml = "0.37.2"
toml = "0.8.19"
parse-wiki-text-2 = { workspace = true }
serde = { workspace = true }
serde_json = "1.0.138"
jiff = { version = "0.1.29", features = ["serde"] }
rayon = "1.10.0"
memmap2 = "0.9.5"

wikitext_util = { path = "wikitext_util" }
open = "5.3.2"
