[package]
name = "wikitext_simplified"
version = "0.1.0"
edition = "2021"

[dependencies]
parse-wiki-text-2 = { workspace = true }
serde = { workspace = true, optional = true }

wikitext_util = { path = "../wikitext_util" }

[features]
serde = ["dep:serde"]
default = []
