name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run Rust tests
        run: cargo test

      - name: Build WASM
        run: wasm-pack build --target web wikitext_simplified -d ../website/wikitext_simplified

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: website/package-lock.json

      - name: Install website dependencies
        working-directory: website
        run: npm ci

      - name: Run wikitext tests
        working-directory: website
        run: npm run test:wikitext
